### ISSUE TITLE
enabling external loggers triggers python errors

### ISSUE THREAD

**Issue by surlypants** [JoeLametta/whipper#111]
Upon enabling (any) external loggers, python promptly vomits with:

```python
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 9, in <module>
    load_entry_point('whipper==0.4.2', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.4.2-py2.7.egg/morituri/command/main.py", line 39, in main
    raise ImportError(e)
ImportError: No module named configure
```

git clones or whipper and all three external loggers as of 20170114

I'm sure I'm missing something small & silly.

thanks in advance

 
```bash
Script started on Sat 14 Jan 2017 04:01:28 PM CST

$ ls ~/.local/share/whipper
ls: cannot access '/home/USER/.local/share/whipper': No such file or directory

$ which whipper
/usr/local/bin/whipper

$ whipper --version
whipper 0.4.2

$ WHIPPER_DEBUG=DEBUG whipper cd rip --help
DEBUG:musicbrainzngs:set user-agent to whipper/0.4.2 python-musicbrainzngs/0.5 ( https://github.com/JoeLametta/whipper )
INFO:morituri.common.config:Loaded 0 sections from config file
usage: whipper cd rip [-h] [-T TOC_PICKLE] [-R RELEASE_ID] [-p] [-c COUNTRY]
                      [-L LOGGER] [-o OFFSET] [-x] [-O OUTPUT_DIRECTORY]
                      [-W WORKING_DIRECTORY] [--track-template TRACK_TEMPLATE]
                      [--disc-template DISC_TEMPLATE] [-U]

Rips a CD. Tracks are named according to the track template, filling in the
variables and adding the file extension. Variables exclusive to the track
template are: - %t: track number - %a: track artist - %n: track title - %s:
track sort name Disc files (.cue, .log, .m3u) are named according to the disc
template, filling in the variables and adding the file extension. Variables
for both disc and track template are: - %A: album artist - %S: album sort name
- %d: disc title - %y: release year - %r: release type, lowercase - %R:
Release type, normal case - %x: audio extension, lowercase - %X: audio
extension, uppercase Paths to track files referenced in .cue and .m3u files
will be made relative to the directory of the disc files. All files will be
created relative to the given output directory. Log files will log the path to
tracks relative to this directory.

optional arguments:
  -h, --help            show this help message and exit
  -T TOC_PICKLE, --toc-pickle TOC_PICKLE
                        pickle to use for reading and writing the TOC
                        (default: None)
  -R RELEASE_ID, --release-id RELEASE_ID
                        MusicBrainz release id to match to (if there are
                        multiple) (default: None)
  -p, --prompt          Prompt if there are multiple matching releases
                        (default: False)
  -c COUNTRY, --country COUNTRY
                        Filter releases by country (default: None)
  -L LOGGER, --logger LOGGER
                        logger to use (choose from 'morituri') (default:
                        morituri)
  -o OFFSET, --offset OFFSET
                        sample read offset (default: None)
  -x, --force-overread  Force overreading into the lead-out portion of the
                        disc. Works only if the patched cdparanoia package is
                        installed and the drive supports this feature.
                        (default: False)
  -O OUTPUT_DIRECTORY, --output-directory OUTPUT_DIRECTORY
                        output directory; will be included in file paths in
                        log (default: .)
  -W WORKING_DIRECTORY, --working-directory WORKING_DIRECTORY
                        working directory; morituri will change to this
                        directory and files will be created relative to it
                        when not absolute (default: None)
  --track-template TRACK_TEMPLATE
                        template for track file naming (default default)
                        (default: %r/%A - %d/%t. %a - %n)
  --disc-template DISC_TEMPLATE
                        template for disc file naming (default default)
                        (default: %r/%A - %d/%A - %d)
  -U, --unknown         whether to continue ripping if the CD is unknown
                        (default: False)



$ cp ~/whipper/plugins/* ~/.local/share/whipper/plugins/

$ ls -l !$
ls -l ~/.local/share/whipper/plugins/
total 52
-rw-r--r-- 1 USER USER 8292 Jan 14 16:03 morituri_eaclogger-0.2.1-py2.7.egg
-rw-r--r-- 1 USER USER 8075 Jan 14 16:03 morituri_whatlogger-0.2.3-py2.7.egg
-rw-r--r-- 1 USER USER 7505 Jan 14 16:03 morituri_yamllogger-0.0.1-py2.7.egg

$ WHIPPER_DEBUG=DEBUG whipper cd rip --help
DEBUG:musicbrainzngs:set user-agent to whipper/0.4.2 python-musicbrainzngs/0.5 ( https://github.com/JoeLametta/whipper )
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 9, in <module>
    load_entry_point('whipper==0.4.2', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.4.2-py2.7.egg/morituri/command/main.py", line 39, in main
    raise ImportError(e)
ImportError: No module named configure

$ exit

Script done on Sat 14 Jan 2017 04:03:35 PM CST
```

**Comment by JoeLametta** [comment]
> I'm sure I'm missing something small & silly.

The errors happens because whipper introduced some [backward incompatible changes](https://github.com/JoeLametta/whipper#backward-incompatible-changes) (the one causing this is PR https://github.com/JoeLametta/whipper/pull/94, which isn't currently included in the README). In order to fix those, the logger plugins needs to be updated replacing the currently invalid import `from morituri.configure import configure`.

Tomorrow I'll update `eaclogger`.
Please delete `yamlogger` because that one is intended only for morituri use (whipper already ships it as internal logger).

Regarding `whatlogger` just remove the plugin until @RecursiveForest updates it.

Thanks for reporting this issue.

**Comment by JoeLametta** [comment]
I've just updated eaclogger: in order to test, remove all the existing plugins and follow [these instructions](https://github.com/JoeLametta/morituri-eaclogger#instructions-for-whipper).

Please let me know if it works correctly.

**Comment by surlypants** [comment]
looks good. thanks.

$ WHIPPER_DEBUG=DEBUG whipper cd rip --help 2>&1 |grep -A2 -- '--logger'
  -L LOGGER, --logger LOGGER
                        logger to use (choose from 'morituri', 'eac')
                        (default: morituri)

**Comment by JoeLametta** [comment]
> looks good. thanks.

Fine.
I haven't tested it against morituri but the updated logger should work correctly even with that one.
