### ISSUE TITLE
Track "can't be ripped" but EAC can :)

### ISSUE THREAD

**Issue by arigit** [JoeLametta/whipper#116]
New CD just purchased, on a calibrated drive that never showed a problem.

Here is the full whipper output: http://pastebin.com/EWpPhWZJ

This is on Fedora 25.

I ran whipper 5 times on this CD, all four times it fails, more often on track 5 but not always.

I ran EAC (latest) on the same linux box under WINE, 5 times, every single time it finishes with no issue. I can guess EAC doesn't verify and re-verify multiple times (like whipper seems to be doing), but I ask: can whipper fallback to EACs behavior with a warning, rather than failing out like so:

Ripping track 10 of 11: 10. Canción de Cuna (remix).flac
Ripping track 10 of 11 (try 2): 10. Canción de Cuna (remix).flac
Ripping track 10 of 11 (try 3): 10. Canción de Cuna (remix).flac
Ripping track 10 of 11 (try 4): 10. Canción de Cuna (remix).flac
Ripping track 10 of 11 (try 5): 10. Canción de Cuna (remix).flac
CRITICAL:morituri.command.cd:Giving up on track 10 after 5 times
Traceback (most recent call last):                 
  File "/usr/bin/whipper", line 9, in <module>
    load_entry_point('whipper==0.4.2', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/morituri/command/main.py", line 31, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/basecommand.py", line 123, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/basecommand.py", line 123, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/cd.py", line 206, in do
    self.doCommand()
  File "/usr/lib/python2.7/site-packages/morituri/command/cd.py", line 505, in doCommand
    ripIfNotRipped(i + 1)
  File "/usr/lib/python2.7/site-packages/morituri/command/cd.py", line 445, in ripIfNotRipped
    "track can't be ripped. "
RuntimeError: track can't be ripped. Rip attempts number is equal to 'MAX_TRIES'

**Comment by JoeLametta** [comment]
Could you try ripping that CD again in order to generate a [debug logfile](https://github.com/JoeLametta/whipper#bug-reports--feature-requests) to inspect?

Thanks

**Comment by JoeLametta** [comment]
Closed (no reply from the OP).
