### ISSUE TITLE
whipper offset find -o OFFSET not working

### ISSUE THREAD

**Issue by Falcon-1** [JoeLametta/whipper#123]
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.4.2', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.4.2-py2.7.egg/morituri/command/main.py", line 30, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.4.2-py2.7.egg/morituri/command/basecommand.py", line 101, in __init__
    self.options
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.4.2-py2.7.egg/morituri/command/basecommand.py", line 101, in __init__
    self.options
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.4.2-py2.7.egg/morituri/command/basecommand.py", line 88, in __init__
    self.handle_arguments()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.4.2-py2.7.egg/morituri/command/offset.py", line 78, in handle_arguments
    self._offsets.append(int(b))
ValueError: invalid literal for int() with base 10: 'OFFSET'

**Comment by JoeLametta** [comment]
Offset is a placeholder for a signed integer value appropriate for the drive you're using with whipper (instructions [here](https://github.com/JoeLametta/whipper#getting-started)).
I'll update whipper's README, adding a practical example, to make it clearer.
