### ISSUE TITLE
fb271f08cdee877795091065c344dcc902d1dcbf breaks HEAD

### ISSUE THREAD

**Issue by MerlijnWajer** [JoeLametta/whipper#129]
Track  1: rip NOT accurate (max confidence      3) [12788f0f], DB [72f66f4e]
Track  2: rip NOT accurate (max confidence      2) [c0748d0a], DB [ef60d3b5]
Track  3: rip NOT accurate (max confidence      2) [c076faed], DB [9657f96f]
Track  4: rip NOT accurate (max confidence      2) [490c8d5c], DB [608a686b]
Track  5: rip NOT accurate (max confidence      3) [a3c4a441], DB [1d77f155]
Track  6: rip NOT accurate (max confidence      3) [67bdb844], DB [93a0a12b]
Track  7: rip NOT accurate (max confidence      2) [2416421b], DB [d24405f9]
Track  8: rip NOT accurate (max confidence      2) [8d709cf1], DB [fe6d0322]
Track  9: rip NOT accurate (max confidence      3) [3e0c171c], DB [9a1a8285]
Track 10: rip NOT accurate (max confidence      3) [39b53206], DB [90a9c672]
Track 11: rip NOT accurate (max confidence      2) [183569a9], DB [8aebe57e]
Track 12: rip NOT accurate (max confidence      2) [dcf051b5], DB [35b9e562]
Track 13: rip NOT accurate (max confidence      3) [11fe6222], DB [9a3e1185]
Track 14: rip NOT accurate (max confidence      3) [b386848e], DB [a4c87806]
Track 15: rip NOT accurate (max confidence      2) [704e2738], DB [11d3cdf8]
Track 16: rip NOT accurate (max confidence      3) [c5fe494c], DB [ecdcca95]
Track 17: rip NOT accurate (max confidence      3) [85e0488f], DB [f93fdb55]
Track 18: rip NOT accurate (max confidence      3) [55825f79], DB [762ab255]
Track 19: rip NOT accurate (max confidence      2) [2508eb46], DB [0751c9e7]
Track 20: rip NOT accurate (max confidence      2) [643b76c5], DB [93c2ca50]
Track 21: rip NOT accurate (max confidence      3) [6e7f6975], DB [1a44da60]
Track 22: rip NOT accurate (max confidence      3) [0ca3e9fe], DB [715dff26]
Track 23: rip NOT accurate (max confidence      3) [480c4cf1], DB [6d783038]
Track 24: rip NOT accurate (max confidence      2) [1a5bda4b], DB [f5de7628]
Track 25: rip NOT accurate (max confidence      2) [99e34eff], DB [f862be3f]
Track 26: rip NOT accurate (max confidence      3) [153128ff], DB [7c42d30e]
Track 27: rip NOT accurate (max confidence      3) [63ff21cd], DB [584b84ab]
Traceback (most recent call last):
  File "/home/merlijn/src/vec/bin/whipper", line 9, in <module>
    load_entry_point('whipper==0.4.2', 'console_scripts', 'whipper')()
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/command/main.py", line 31, in main
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/command/basecommand.py", line 123, in do
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/command/basecommand.py", line 123, in do
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/command/cd.py", line 207, in do
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/command/cd.py", line 576, in doCommand
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/common/program.py", line 697, in writeLog
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/result/logger.py", line 19, in log
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/result/logger.py", line 112, in logRip
  File "/home/merlijn/src/vec/lib/python2.7/site-packages/whipper-0.4.2-py2.7.egg/morituri/result/logger.py", line 175, in trackLog
NameError: global name 't' is not defined

**Comment by MerlijnWajer** [comment]
Fixed in 0e395e5f0e35a29963451a51f0aeb46564f49bd3
