### ISSUE TITLE
Ripping mixed-mode CDs

### ISSUE THREAD

**Issue by Amitari** [JoeLametta/whipper#142]
When trying to rip a mixed-mode CD (at least when the data track is at the start), Whipper just crashes. I have some game CDs that have to be properly ripped pretty urgently since they might start to rot soon, so the ability to rip mixed-mode would be very appreciated.

> [user@halebopp ~]$ whipper cd -d /dev/sr0 rip
Using configured read offset 6
Checking device /dev/sr0
CDDB disc id: 840e4509
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.4.2', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/morituri/command/main.py", line 31, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/basecommand.py", line 123, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/basecommand.py", line 123, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/cd.py", line 122, in do
    self.mbdiscid = self.ittoc.getMusicBrainzDiscId()
  File "/usr/lib/python2.7/site-packages/morituri/image/table.py", line 348, in getMusicBrainzDiscId
    values = self._getMusicBrainzValues()
  File "/usr/lib/python2.7/site-packages/morituri/image/table.py", line 464, in _getMusicBrainzValues
    assert not self.tracks[-1].audio
AssertionError
[user@halebopp ~]$

**Comment by MerlijnWajer** [comment]
I have some patches for this. Do you want to rip only the audio - or the data tracks as well? And do you expect whipper to do both?

**Comment by Amitari** [comment]
I only expect Whipper to rip the audio only, since ripping audio CDs is it's purpose.

**Comment by JoeLametta** [comment]
Related to #183 & #170.
