### ISSUE TITLE
Accurip verification step failure

### ISSUE THREAD

**Issue by Q3CPMA** [JoeLametta/whipper#178]
Another failure,
```
> whipper cd rip
...
Ripping track 14 of 14: 14. Edge of Sanity - When All Is Said.flac
Checksums match for track 14
Peak level: 96.93%
Rip quality: 100.00%
AccurateRip URL http://www.accuraterip.com/accuraterip/9/0/7/dBAR-014-001cd709-0136ea97-b00d7f0e.bin
7 AccurateRip reponses found
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/morituri/common/checksum.py", line 73, in _arc
    self._wave, self._v2)
  File "/usr/lib64/python2.7/site-packages/morituri/program/arc.py", line 24, in accuraterip_checksum
    stdout=PIPE, stderr=PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/whipper", line 11, in <module>
    load_entry_point('whipper==0.5.1', 'console_scripts', 'whipper')()
  File "/usr/lib64/python2.7/site-packages/morituri/command/main.py", line 31, in main
    ret = cmd.do()
  File "/usr/lib64/python2.7/site-packages/morituri/command/basecommand.py", line 123, in do
    return self.cmd.do()
  File "/usr/lib64/python2.7/site-packages/morituri/command/basecommand.py", line 123, in do
    return self.cmd.do()
  File "/usr/lib64/python2.7/site-packages/morituri/command/cd.py", line 206, in do
    self.doCommand()
  File "/usr/lib64/python2.7/site-packages/morituri/command/cd.py", line 573, in doCommand
    self.program.getAccurateRipResults()) + "\n")
  File "/usr/lib64/python2.7/site-packages/morituri/common/program.py", line 673, in getAccurateRipResults
    trackResult.number
AssertionError: no trackResult.ARCRC on non-HTOA track 1
```

**Comment by JoeLametta** [comment]
Please see [this comment](https://github.com/JoeLametta/whipper/issues/177#issuecomment-315346631) in #177.
