### ISSUE TITLE
AttributeError: RipResult instance has no attribute 'profileName'

### ISSUE THREAD

**Issue by ace214** [JoeLametta/whipper#181]
I'm getting a traceback error. I'm using the Arch package with the eac logger. 
This happens right after the AccurateRip track checks.

====

Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.5.1', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/morituri/command/main.py", line 31, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/basecommand.py", line 123, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/basecommand.py", line 123, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/morituri/command/cd.py", line 206, in do
    self.doCommand()
  File "/usr/lib/python2.7/site-packages/morituri/command/cd.py", line 578, in doCommand
    self.program.writeLog(discName, self.logger)
  File "/usr/lib/python2.7/site-packages/morituri/common/program.py", line 697, in writeLog
    log = logger.log(self.result)
  File "/usr/lib/python2.7/site-packages/eaclogger/logger/eac.py", line 44, in log
    lines = self.logRip(ripResult, epoch=epoch)
  File "/usr/lib/python2.7/site-packages/eaclogger/logger/eac.py", line 114, in logRip
    ripResult.profileName)
AttributeError: RipResult instance has no attribute 'profileName'

**Comment by RecursiveForest** [comment]
Could you run again with the environment variables `WHIPPER_DEBUG=debug` and `WHIPPER_LOGFILE=whipper-$(date -I).log` and uploading the logfile?

**Comment by JoeLametta** [comment]
Thanks for reporting this issue. It should happen only using the external morituri-eaclogger plugin which, unfortunately, hasn't been kept up to date with whipper's latest updates.
Please keep in mind that I consider that logger as legacy. If I'm going to fix it (I'm not sure), I'll probably do it at the end of August.

**Comment by JoeLametta** [comment]
@ace214 

Forgot to add: could you close this issue and open it [here](https://github.com/JoeLametta/morituri-eaclogger/issues/new)? (morituri-eaclogger's issue tracker)

**Comment by JoeLametta** [comment]
Closed (not directly related to whipper).
