### ISSUE TITLE
Whipper crashes while AccurateRip track checks

### ISSUE THREAD

**Issue by gorgobacka** [JoeLametta/whipper#193]
While testing the updated version on a CD with a data track at the end, whipper seems to crash when checking the tracks against AccurateRip.

Log file attached.

@RecursiveForest This might be related to your AccurateRip V2 PR. Maybe you have an idea why this error occurs.

[whipper.log.gz](https://github.com/JoeLametta/whipper/files/1310393/whipper.log.gz)

**Comment by RecursiveForest** [comment]
It looks like the issue is it can't find the AccurateRip entry; it's definitely a bug if whipper crashes (can you paste console output?), but can you confirm what happens with a version of whipper before the commit came in? (I understand this may be difficult because JoeLametta neglected to squash merge…)

**Comment by gorgobacka** [comment]
Here is the console output (the interesting part):

```
....
CRCs match for track 16                    
Peak level: 92.72% 
Rip quality: 100.00%
AccurateRip entry not found                       
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper', 'console_scripts', 'whipper')()
  File "/home/XXXXX/Documents/Programming/whipper/whipper/command/main.py", line 32, in main
    ret = cmd.do()
  File "/home/XXXXX/Documents/Programming/whipper/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/home/XXXXX/Documents/Programming/whipper/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/home/XXXXX/Documents/Programming/whipper/whipper/command/cd.py", line 190, in do
    self.doCommand()
  File "/home/XXXXX/Documents/Programming/whipper/whipper/command/cd.py", line 492, in doCommand
    accurip.print_report(self.program.result)
  File "/home/XXXXX/Documents/Programming/whipper/whipper/common/accurip.py", line 249, in print_report
    if track.AR['DBMaxConfidence'] is not None:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Tomorrow, I will try again with a different commit and will report back. However, I think I tried this CD before and it worked.

**Comment by RecursiveForest** [comment]
I'm pretty confident I know what's causing the bug, so I'll try to work a fix tonight. The issue is related to the code not supporting discs with data tracks properly (because I don't have any to test with).

**Comment by RecursiveForest** [comment]
@gorgobacka , does whipper report the CD as found in the accuraterip database in previous versions? If so, could you paste the accuraterip URL? (Or better yet, paste the entire console output & debug log from a succesful run with a previous version.)

**Comment by gorgobacka** [comment]
@RecursiveForest unfortunately, it seems that CD is not present in the accuraterip database.

I went back to commit https://github.com/JoeLametta/whipper/commit/7ae27de32bcd3cc59b98a8388aa0f48e48120c8e and the rip worked fine.

Here are the console output & debug log:
[whipper_console_output.log.gz](https://github.com/JoeLametta/whipper/files/1316910/whipper_console_output.log.gz)
[whipper.log.gz](https://github.com/JoeLametta/whipper/files/1316909/whipper.log.gz)

**Comment by JoeLametta** [comment]
@gorgobacka Does it still happen?

To me it seems related to #196.

**Comment by gorgobacka** [comment]
I will check again.

**Comment by gorgobacka** [comment]
I get the same error as before with the same CD. Logfiles added.

[console_output.txt.gz](https://github.com/JoeLametta/whipper/files/1885511/console_output.txt.gz)
[whipper.log.gz](https://github.com/JoeLametta/whipper/files/1885512/whipper.log.gz)

(If it's the same error, it one issue can be close. But I'm not sure.)

**Comment by MerlijnWajer** [comment]
I should have code to fix this somewhere...

**Comment by JoeLametta** [comment]
> I get the same error as before with the same CD. Logfiles added.

Thanks!
Please see @RecursiveForest's [comment](https://github.com/JoeLametta/whipper/issues/196#issuecomment-342020213): to test that hypothesis could you backup your whipper cache folder and check if moving it away solves the issue?
