### ISSUE TITLE
ImportError - CDDB on Solus.

### ISSUE THREAD

**Issue by Matt07211** [JoeLametta/whipper#209]
```$ whipper cd rip -p -U --track-template='%A/(%y) %d/%t. %n' --disc-template='%A/(%y) %d/%A - %d'
Using configured read offset 102
Checking device /dev/sr0
CDDB disc id: 1e058e04
MusicBrainz disc id s7bBiNWB_vbWQ9ZPDOLy6waw1hw-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+4+106812+150+18715+45387+75137&tracks=4&id=s7bBiNWB_vbWQ9ZPDOLy6waw1hw-
Disc duration: 00:23:42.160, 4 audio tracks
WARNING:whipper.common.program:release not found: NotFoundException(ResponseError(),)
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.5.1', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper-0.5.1-py2.7.egg/whipper/command/main.py", line 32, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper-0.5.1-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper-0.5.1-py2.7.egg/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper-0.5.1-py2.7.egg/whipper/command/cd.py", line 129, in do
    cddbmd = self.program.getCDDB(cddbid)
  File "/usr/lib/python2.7/site-packages/whipper-0.5.1-py2.7.egg/whipper/common/program.py", line 258, in getCDDB
    import CDDB
ImportError: No module named CDDB
```

I installed all the dependices I compiled whipper from source yesterday.
```
sudo eopkg it libcdio-paranoia cdrdao python-gobject2 python-musicbrainzngs mutagen python-setuptools libcddb libcdio libcdio-devel python-requests libsndfile libsndfile-devel libflac sox
```
and
```
sudo pip install pycdio==0.20
```

So far every other CD has ripped fine, but thats because they where already in the Musicbrainz database.
The CD Im trying to rip is "The Prodigy - Voodoo People".

Currently using Solus with all packages up to date, running Linux kernel 4.14.8-41 and 
```
$ python -V
Python 2.7.13
$ python3 -V
Python 3.5.4
```
Any other information needed, just let me know.

**Comment by JoeLametta** [comment]
Hi, you also need to install the [python-cddb](http://cddb-py.sourceforge.net/) package.
Please try and let me know if it solves your problem.

Thanks,
Joe

**Comment by Matt07211** [comment]
Yes i can verify it works, I'm not sure how I overlooked it on my part, I'll close the issue.
