### ISSUE TITLE
Import Error No Module Named gobject Fedora 26 and 27

### ISSUE THREAD

**Issue by rry1983** [JoeLametta/whipper#228]
I have used the copr repository in the past as a quick way to install whipper on Fedora.  Starting with Fedora 26 and occurring with Fedora 27 I can install whipper just fine, the problem appears when I run it.  When I try to execute whipper drive analyze, whipper offset find or whipper rip cd I receive the following error:

Traceback (most recent call last):
  File "/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.6.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/whipper/command/main.py", line 11, in <module>
    from whipper.command import cd, offset, drive, image, accurip, debug
  File "/usr/lib/python2.7/site-packages/whipper/command/cd.py", line 27, in <module>
    import gobject
ImportError: No module named gobject

I have checked around the copr repository for a contact for mruszczyk but can not find one.  I have checked through dependencies and seem to have them all installed at the versions recommended.  I can successfully build from source and run whipper perfectly fine on Debian but no luck on Fedora.

**Comment by mruszczyk** [comment]
I’m here. I will double check this when I get home in a few hours.

**Comment by mruszczyk** [comment]
I have just updated the Copr repo with build 0.6.0-3. Please give that version a test to see if that runs properly.

**Comment by rry1983** [comment]
Just tested the new build.  It installs and runs perfectly.  Thank you.
