### ISSUE TITLE
Can't rip last track on a CD with 99 tracks

### ISSUE THREAD

**Issue by fturco** [JoeLametta/whipper#302]
I can't rip the last track of a CD with 99 tracks. I tried the following command:

    $ WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper cd rip -R 5cdfa69d-7b0c-3579-af99-901b03fe33ea

Everything went well until the last track:

```
...
Ripping track 99 of 99: 99 [unknown].flac
Ripping track 99 of 99 (try 2): 99 [unknown].flac
Ripping track 99 of 99 (try 3): 99 [unknown].flac
Ripping track 99 of 99 (try 4): 99 [unknown].flac
Ripping track 99 of 99 (try 5): 99 [unknown].flac
track can't be ripped. Rip attempts number is equal to 'MAX_TRIES'
```

[whipper.log.gz](https://github.com/JoeLametta/whipper/files/2447364/whipper.log.gz)

Some more info:

```
$ whipper drive list
drive: /dev/cdrom, vendor: PLEXTOR , model: DVDR   PX-830SA , release: 1.01
       Configured read offset: 96
       Can defeat audio cache: True
```

I'm using `media-sound/whipper-0.7.0` on a Gentoo Linux system.

**Comment by JoeLametta** [comment]
Thanks for reporting this issue!
Could you post the output of the following command?

`libcdio-paranoia --stderr-progress --sample-offset=96 --force-cdrom-device /dev/sr0 99[00:00:00.00]-99[00:01:39.14] "$HOME/track_99.wav"`

If that fails you may need to: `umount /dev/sr0` first.

**Comment by fturco** [comment]
It immediately fails with the following error message:

```
$ libcdio-paranoia --stderr-progress --sample-offset=96 --force-cdrom-device /dev/sr0 99[00:00:00.00]-99[00:01:39.14] $HOME/track_99.wav
Sending all callback output to stderr for wrapper script
cdparanoia III release 10.2 libcdio 2.0.0 x86_64-pc-linux-gnu
(C) 2001 Monty <monty@xiph.org> and Xiphophorus
(C) 2004, 2005, 2008 Rocky Bernstein <rocky@gnu.org>
(C) 2014 Robert Kausch <robert.kausch@freac.org>

Report bugs to bug-libcdio@gnu.org

Time/sector offset goes beyond end of specified track.
```

**Comment by JoeLametta** [comment]
Uhm... given the error message the issue seems similar to the one reported in #234 (and https://github.com/rocky/libcdio-paranoia/issues/14).

Could you please install [Xiph's cdparanoia](https://packages.gentoo.org/packages/media-sound/cdparanoia) and post the output of the following command?

`cdparanoia --stderr-progress --sample-offset=96 --force-cdrom-device /dev/sr0 99[00:00:00.00]-99[00:01:39.14] "$HOME/track_99_cdparanoia.wav"`

Cheers,
Joe

**Comment by fturco** [comment]
[cdparanoia.log.gz](https://github.com/JoeLametta/whipper/files/2456820/cdparanoia.log.gz)

I used the following command:

    cdparanoia-paranoia --stderr-progress --sample-offset=96 --force-cdrom-device /dev/sr0 99[00:00:00.00]-99[00:01:39.14] ~/track_99_cdparanoia.wav > cdparanoia.log 2>&1

On my system `cdparanoia-paranoia` is Xiph's one, while `libcdio-paranoia` is the updated one.

Some info about the output track:

```
$ du -b track_99_cdparanoia.wav 
17498924	track_99_cdparanoia.wav
```

```
$ mediainfo track_99_cdparanoia.wav 
General
Complete name                            : track_99_cdparanoia.wav
Format                                   : Wave
File size                                : 16.7 MiB
Duration                                 : 1 min 39 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 411 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 1 min 39 s
Bit rate mode                            : Constant
Bit rate                                 : 1 411.2 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 16.7 MiB (100%)
```

**Comment by JoeLametta** [comment]
All right, that confirms my suspicion: unfortunately this issue seems to be caused by a bug in `libcdio-paranoia` (probably similar to the one reported in https://github.com/rocky/libcdio-paranoia/issues/14).

**Comment by Bujiraso** [comment]
I'm also seeing this one and let some comments on #474

**Comment by snorfalorpagus** [comment]
Same issue trying to rip "Nine Inch Nails - Broken" which has 99 tracks.

```
$ cdparanoia --version
cdparanoia III release 10.2 (September 11, 2008)

$ cd-paranoia --version
cdparanoia III release 10.2 libcdio 2.1.0 x86_64-pc-linux-gnu
(C) 2001 Monty <monty@xiph.org> and Xiphophorus
(C) 2004, 2005, 2008 Rocky Bernstein <rocky@gnu.org>
(C) 2014 Robert Kausch <robert.kausch@freac.org>

Report bugs to bug-libcdio@gnu.org
```

Installed whipper via pacman on Arch.

```
Traceback (most recent call last):               
  File "/usr/lib/python3.13/site-packages/whipper/program/cdparanoia.py", line 193, in getTrackQuality
    return min(frames * 2.0 / reads, 1.0)
               ~~~~~~~~~~~~~^~~~~~~
ZeroDivisionError: float division by zero

...

RuntimeError: cdparanoia couldn't read any frames for the current track
INFO:whipper.command.cd:ripping track 99 of 99 (try 5): 99 - Nine Inch Nails - Suck.flac
WARNING:whipper.program.cdparanoia:because of a cd-paranoia upstream bug whipper may fail to rip the last track of a CD when it has got 99 of them. For more details please check the following issue: https://github.com/whipper-team/whipper/issues/302
```

Is there a workaround for this?

**Comment by Rendrox** [comment]
Having the same issue with "Nine Inch Nails - Broken" as well...

**Comment by Meowsod** [comment]
Same problem with https://musicbrainz.org/release/d3236119-0934-4625-a022-14ceb03c18e5, cyanrip doesn't appear to have this issue though
```py
INFO:whipper.command.cd:ripping track 99 of 99 (try 10): 1-99. Timbuctoo.flac
WARNING:whipper.program.cdparanoia:because of a cd-paranoia upstream bug whipper may fail to rip the last track of a CD when it has got 99 of them. For more details please check the following issue: https://github.com/whipper-team/whipper/issues/302
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 1945148
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/whipper/program/cdparanoia.py", line 193, in getTrackQuality
    return min(frames * 2.0 / reads, 1.0)
               ~~~~~~~~~~~~~^~~~~~~
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/whipper/extern/task/task.py", line 523, in c
    callable_task(*args, **kwargs)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/whipper/program/cdparanoia.py", line 324, in _read
    self._done()
    ~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/program/cdparanoia.py", line 400, in _done
    self.quality = self._parser.getTrackQuality()
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/whipper/program/cdparanoia.py", line 195, in getTrackQuality
    raise RuntimeError("cdparanoia couldn't read any frames "
                       "for the current track")
RuntimeError: cdparanoia couldn't read any frames for the current track
CRITICAL:whipper.command.cd:giving up on track 99 after 10 times
("track can't be ripped. Rip attempts number is equal to %d", 10)
```

**Comment by hadess** [comment]
I ran into a problem with `whipper-0.10.0-17.fc42.x86_64` and `libcdio-paranoia-10.2+2.0.2-4.fc42.x86_64` trying to rip this promo CD that splits up the 17 tracks into 99 tracks so it couldn't easily be ripped:
https://people.redhat.com/bnocera/99-tracks-audio-cd.rar

But I guess that this should work for whipper to have a chance, so do we need to file a new cd-paranoia bug?
```
$ cd-paranoia --stderr-progress --sample-offset=6 --force-cdrom-device /dev/sr0 -B 99-99 track_99.wav
Sending all callback output to stderr for wrapper script
cdparanoia III release 10.2 libcdio 2.1.0
(C) 2001 Monty <monty@xiph.org> and Xiphophorus
(C) 2004, 2005, 2008 Rocky Bernstein <rocky@gnu.org>
(C) 2014 Robert Kausch <robert.kausch@freac.org>

Report bugs to bug-libcdio@gnu.org

Selected span contains non audio track at track 101.  Aborting.
```
