### ISSUE TITLE
offset find fails

### ISSUE THREAD

**Issue by NicoHood** [JoeLametta/whipper#46]
```
[arch@arch Music]$ rip offset find
Checking device /dev/cdrom
eject: CD-ROM tray close command failed: Input/output error
Trying read offset 6 ...                      
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Offset of device is likely 6, confirming ...  
                                              
Read offset of device is: 6.
Adding read offset to configuration file.
Traceback (most recent call last):
  File "/usr/bin/rip", line 36, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 40, in main
    ret = c.parse(argv)
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 116, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/site-packages/morituri/rip/offset.py", line 200, in do
    self._foundOffset(device, offset)
  File "/usr/lib/python2.7/site-packages/morituri/rip/offset.py", line 248, in _foundOffset
    offset)
  File "/usr/lib/python2.7/site-packages/morituri/common/config.py", line 89, in setReadOffset
    section = self._findOrCreateDriveSection(vendor, model, release)
  File "/usr/lib/python2.7/site-packages/morituri/common/config.py", line 160, in _findOrCreateDriveSection
    self.write()
  File "/usr/lib/python2.7/site-packages/morituri/common/config.py", line 62, in write
    shutil.move(path, self._path)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'/home/arch/.config/whipper/whipper.conf'
```

**Comment by JoeLametta** [comment]
That's unrelated to rip offset find (https://github.com/JoeLametta/whipper/commit/746dc6599d8c0ff6437f6c47142daefef1924097).
Documented [here](https://github.com/JoeLametta/whipper#backward-incompatible-changes).

@neitsab will update archlinux's AUR package to include a warning about this change.

**Comment by JoeLametta** [comment]
There was a bug related to the update (fixed now).
Read the README, then please test again and let me know how it goes...

**Comment by NicoHood** [comment]
I don't get what you are trying to tell me.
The problem to me seems that `~/.config/whipper` does not exists yet and whipper simply has to create the path if it does not exist yet. It would be a shame if thats required by the user. However this seems to not work. (I am not using XDG, or at least it seems to not provide those variabled for me on arch).

**Comment by JoeLametta** [comment]
> I don't get what you are trying to tell me.

Sorry, I'll try to be clearer...

> The problem to me seems that ~/.config/whipper does not exists yet and whipper simply has to create the path if it does not exist yet. It would be a shame if thats required by the user.

You're right and that's the "bug related to the update" I referred to in my previous message (already fixed).

> However this seems to not work. (I am not using XDG, or at least it seems to not provide those variabled for me on arch).

The bug should have been fixed with https://github.com/JoeLametta/whipper/commit/8b5ce57fcd9c6e7bbb961f22fa62215a2aa0675a. I've just tested `rip offset find` and here it works fine (unable to replicate), please update whipper and test again.

Thanks for the feedback

PS: It should work fine even without XDG environment variables set.

**Comment by NicoHood** [comment]
It now works, but it seems to be unable to find an offset. Is this normal? From my old notes I must have offset 6, but this time that was not recognized. However Accurate rip reports no errors with offset 6, but I have little knowledge about those parameters.

```
[arch@arch Music]$ rip offset find
Checking device /dev/cdrom
eject: CD-ROM tray close command failed: Input/output error
Trying read offset 6 ...                      
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Trying read offset 48 ...                     
Trying read offset 102 ...                    
Trying read offset 667 ...                    
Trying read offset 12 ...                     
Trying read offset 30 ...                     
Trying read offset 618 ...                    
Trying read offset 594 ...                    
Trying read offset 738 ...                    
Trying read offset -472 ...                   
WARNING: cannot rip with offset -472...       
Trying read offset 98 ...
Trying read offset 116 ...                    
Trying read offset 96 ...                     
Trying read offset 733 ...                    
Trying read offset 120 ...                    
Trying read offset 691 ...                    
Trying read offset 685 ...                    
Trying read offset 97 ...                     
Trying read offset 600 ...                    
Trying read offset 690 ...                    
Trying read offset 1292 ...                   
Trying read offset 99 ...                     
Trying read offset 676 ...                    
Trying read offset 686 ...                    
Trying read offset 1182 ...                   
Trying read offset -24 ...                    
WARNING: cannot rip with offset -24...        
Trying read offset 704 ...
Trying read offset 572 ...                    
Trying read offset 688 ...                    
Trying read offset 91 ...                     
Trying read offset 696 ...                    
Trying read offset 103 ...                    
Trying read offset -491 ...                   
WARNING: cannot rip with offset -491...       
Trying read offset 689 ...
Trying read offset 145 ...                    
Trying read offset 708 ...                    
Trying read offset 697 ...                    
Trying read offset 564 ...                    
Trying read offset 86 ...                     
Trying read offset 679 ...                    
Trying read offset 355 ...                    
Trying read offset -496 ...                   
WARNING: cannot rip with offset -496...       
Trying read offset -1164 ...
WARNING: cannot rip with offset -1164...      
Trying read offset 1160 ...
Trying read offset 694 ...                    
Trying read offset 0 ...                      
Trying read offset -436 ...                   
WARNING: cannot rip with offset -436...       
Trying read offset 79 ...
Trying read offset 94 ...                     
Trying read offset 684 ...                    
Trying read offset 681 ...                    
Trying read offset 106 ...                    
Trying read offset 692 ...                    
Trying read offset 943 ...                    
Trying read offset 1194 ...                   
Trying read offset 92 ...                     
Trying read offset 117 ...                    
Trying read offset 680 ...                    
Trying read offset 682 ...                    
Trying read offset 1268 ...                   
Trying read offset 678 ...                    
Trying read offset -582 ...                   
WARNING: cannot rip with offset -582...       
Trying read offset 1473 ...
Trying read offset 1279 ...                   
Trying read offset -54 ...                    
WARNING: cannot rip with offset -54...        
Trying read offset 1508 ...
Trying read offset 740 ...                    
Trying read offset 1272 ...                   
Trying read offset 534 ...                    
Trying read offset 976 ...                    
Trying read offset 687 ...                    
Trying read offset 675 ...                    
Trying read offset 1303 ...                   
Trying read offset 674 ...                    
Trying read offset 1263 ...                   
Trying read offset 108 ...                    
Trying read offset 974 ...                    
Trying read offset 122 ...                    
Trying read offset 111 ...                    
Trying read offset -489 ...                   
WARNING: cannot rip with offset -489...       
Trying read offset 772 ...
Trying read offset 732 ...                    
Trying read offset -495 ...                   
WARNING: cannot rip with offset -495...       
Trying read offset -494 ...
WARNING: cannot rip with offset -494...       
Trying read offset 975 ...
Trying read offset 935 ...                    
Trying read offset 87 ...                     
Trying read offset 668 ...                    
Trying read offset 1776 ...                   
Trying read offset 1364 ...                   
Trying read offset 1336 ...                   
Trying read offset 1127 ...                   
No matching offset found.                     
Consider trying again with a different disc.
```

**Comment by JoeLametta** [comment]
> It now works, but it seems to be unable to find an offset. Is this normal?

Unfortunately it's not rare (`rip offset find` is unreliable, it's planned to be rewritten in a better way).

> From my old notes I must have offset 6, but this time that was not recognized. However Accurate rip reports no errors with offset 6, but I have little knowledge about those parameters.

If you're in doubt the easier way to find the right offset is to look up it [here](www.accuraterip.com/driveoffsets.htm).

**Comment by NicoHood** [comment]
The link you posted is unreachable. 404

**Comment by neitsab** [comment]
@NicoHood Here you go: www.accuraterip.com/driveoffsets.htm

(the link was simply appended by mistake to https://github.com/JoeLametta/whipper/issues/, making it invalid. You can identify such situations by looking at the link URL.)

**Comment by JoeLametta** [comment]
Yup, fixed it now.
