### ISSUE TITLE
can't find accuraterip-checksum binary in morituri-uninstalled mode

### ISSUE THREAD

**Issue by kevmitch** [JoeLametta/whipper#47]
In morituri-uninstalled mode, I am now getting 
```
$ rip offset find
Checking device /dev/cdrom
Trying read offset 6 ...                      
Traceback (most recent call last):            1 %      
  File "/home/kevmitch/src/whipper/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/home/kevmitch/src/whipper/morituri/common/checksum.py", line 292, in _arc
    self._wave, self._v2)
  File "/home/kevmitch/src/whipper/morituri/program/arc.py", line 22, in accuraterip_checksum
    stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

This is fixed by copying the accuraterip-checksum binary to the bin directory. Trouble is, I can't figure out how to get the build system to do that.

**Comment by MerlijnWajer** [comment]
Presuming that morituri-uninstalled sets a PYTHONPATH, simply making sure that it either sets the PATH properly or installs accuraterip-checksum to bin/ should do the trick. I'll see what I can do to fix it.

**Comment by MerlijnWajer** [comment]
Presumably the problem is that automake will only move the binary to the right bin folder when 'make install' is issued. So one fix would be for morituri-uninstalled to add the src/ dir to the PATH variable, or otherwise ensure that somehow accuraterip-checksum ends up in the bin/ folder, which actually issuing make install. That is kind of tricky.

**Comment by RecursiveForest** [comment]
With the change to setuptools, the nature of this bug has changed a bit. Right now there are no provisions for automatically installing accuraterip-checksum anywhere from setuptools: you have to `cd src && sudo make install`, as documented in the README.

The simplest and most canonical approach is to either build arc with simple `make` and copy it to somewhere in your $PATH (which you've probably extended to something like ~/bin anyways), or to do something similar and put it into a venv.

There is also the option of having setuptools handle the arc depedency (either by invoking `make install` or by invoking `make` and then using setuptools to install it), but both slightly obfuscate the process for the package maintainers and require more work on our end.

**Comment by RecursiveForest** [comment]
So what do we want to do here? I'm in favour of closing the bug and doing nothing, as the documentation covers what one should do in this circumstance.

**Comment by JoeLametta** [comment]
> So what do we want to do here? I'm in favour of closing the bug and doing nothing, as the documentation covers what one should do in this circumstance.

Yeah maybe it can also be mentioned in the README (running uninstalled OR backward incompatible changes).

**Comment by MerlijnWajer** [comment]
Isn't it possible to have setuptools just build the binary when running setup.py? That'd be similar to 'make' without 'make install'.

**Comment by RecursiveForest** [comment]
It is, but since you'd have to handle the install yourself we might as well let the user run `make` too. I think the few lines of setup.py code are not worth saving the user 5 characters of typing, which they'd have to do anyways if their `config.mk` settings aren't the same.

**Comment by neitsab** [comment]
Packaging question: is accuraterip-checksum a hard/optional dependency of whipper? It is not listed in README#Requirements, only mentioned later as a bundled dep (which is not built automatically anymore since the move to setuptools, if I understand correctly).

**Comment by MerlijnWajer** [comment]
Yes, please package it. It is not optional in the sense that our current code expects it to be installed - there is no fallback to the gst version.

Can't setuptools also issue make, or perhaps compile the binary automatically? I think setuptools had ways to compile C code as well, so we can also use that instead of the makefile.

**Comment by ArchangeGabriel** [comment]
The best would be to depend on the actual packaged accuraterip-checksum, eventually while trying harder to get https://github.com/leo-bogert/accuraterip-checksum/pull/3 accepted or proposing this patch to respective accuraterip-checksum package maintainers.
