### ISSUE TITLE
CD-TEXT issue

### ISSUE THREAD

**Issue by thomas-mc-work** [JoeLametta/whipper#49]
I tried to rip a CD that oviously contains CD-TEXT. I got this error message:

    ...
    Scanning indexes of session 1... (2 of 2) ...  98 %
    Scanning indexes of session 1... (2 of 2) ...  99 %
    Scanning indexes of session 1... (2 of 2) ... 100 %
                                                   
    Scanning indexes of session 1... (2 of 2) ... 100 %
    
    Traceback (most recent call last):
      File "/usr/local/bin/rip", line 37, in <module>
        sys.exit(main.main(sys.argv[1:]))
      File "/usr/local/lib/python2.7/site-packages/morituri/rip/main.py", line 40, in main
        ret = c.parse(argv)
      File "/usr/local/lib/python2.7/site-packages/morituri/rip/main.py", line 118, in parse
        logcommand.LogCommand.parse(self, argv)
      File "/usr/local/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
        command.Command.parse(self, argv)
      File "/usr/local/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
        return self.subCommands[command].parse(args[1:])
      File "/usr/local/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
        command.Command.parse(self, argv)
      File "/usr/local/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
        return self.subCommands[command].parse(args[1:])
      File "/usr/local/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
        command.Command.parse(self, argv)
      File "/usr/local/lib/python2.7/site-packages/morituri/extern/command/command.py", line 363, in parse
        ret = self.do(args)
      File "/usr/local/lib/python2.7/site-packages/morituri/rip/cd.py", line 128, in do
        self.ittoc.getMusicBrainzDiscId(), self.device, offset)
      File "/usr/local/lib/python2.7/site-packages/morituri/common/program.py", line 177, in getTable
        runner.run(t)
      File "/usr/local/lib/python2.7/site-packages/morituri/extern/task/task.py", line 490, in run
        raise TaskException(task.exception, message=msg)
    morituri.extern.task.task.TaskException: (ProgramError('Reading of CD-TEXT data failed.',), None)

Maybe it's possible to simply omit tracks in this format before trying to read?

It is this CD (maybe this helps): https://musicbrainz.org/release/75fab53f-68a1-4f37-ab5d-d71a316e84ad

**Comment by JoeLametta** [comment]
This is a cdrdao issue but whipper shouldn't stop ripping. I haven't go a lot of free time these days but I'll try to debug this issue as soon as possible. Maybe I'll ask you to try ripping that same CD using cdrdao.

Anyway here's a related issue:

https://github.com/thomasvs/morituri/issues/143

**Comment by JoeLametta** [comment]
It seems that whipper doesn't check the message log level before reporting firing the ProgramError...

Straight from cdrdao source code:

```c++
if (opts->withCddb) {
    if (readCddb(opts, toc) == 0)
        log_message(2, "CD-TEXT data was added to toc-file.");
    else
        log_message(2, "Reading of CD-TEXT data failed - "
                    "continuing without CD-TEXT data.");
}
```

```c++
// Level definitions:
//   -1 : warning
//   -2 : error
//   -3 : internal error
//   -4 to -9 : fatal error
//   -10 and less : fatal error, call will exit the calling thread.
//
// Levels >= 0 are controlled by the verbosity set below.
```

**Comment by JoeLametta** [comment]
@thomas-mc-work Could you try updating whipper and ripping that same CD again? (now, thanks to RecursiveForest pull request, it should work as expected).
Let me know how it goes.

Thanks.

**Comment by thomas-mc-work** [comment]
Perfect, it's working now  :thumbsup:
Thank you!
