### ISSUE TITLE
ERROR: stopping task which is already stopped

### ISSUE THREAD

**Issue by aereaux** [JoeLametta/whipper#59]
When ripping a certain track, I get this error:

``` python
ERROR: stopping task which is already stopped
  File "/usr/bin/rip", line 11, in <module>
    load_entry_point('whipper==0.3.0', 'console_scripts', 'rip')()
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 22, in main
    ret = c.parse(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 89, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/site-packages/morituri/rip/cd.py", line 174, in do
    self.doCommand()
  File "/usr/lib/python2.7/site-packages/morituri/rip/cd.py", line 482, in doCommand
    ripIfNotRipped(i + 1)
  File "/usr/lib/python2.7/site-packages/morituri/rip/cd.py", line 414, in ripIfNotRipped
    number, len(self.itable.tracks), extra))
  File "/usr/lib/python2.7/site-packages/morituri/common/program.py", line 603, in ripTrack
    runner.run(t)
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 479, in run
    self._loop.run()
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/gstreamer.py", line 151, in stop
    task.Task.stop(self)
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 154, in stop
    import traceback; traceback.print_stack()
```

It happens multiple times, when the ripper retries.

**Comment by RecursiveForest** [comment]
Can you:
```bash
RIP_DEBUG=5 rip offset find > whipper.log 2>&1
gzip whipper.log
```
And upload the log?

**Comment by aereaux** [comment]
[whipper.log.gz](https://github.com/JoeLametta/whipper/files/563216/whipper.log.gz)

**Comment by stochashtic** [comment]
Just installed whipper and having the same error on all cds that I try.  I used to use the old morituri package.

` Ripping track 1 of 16: 01. Steven Wright - And Now Little Green Bag….flac
Ripping track 1 of 16 (try 2): 01. Steven Wright - And Now Little Green Bag….flac
ERROR: stopping task which is already stopped
  File "/usr/bin/whipper", line 9, in <module>
    load_entry_point('whipper==0.4.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/main.py", line 27, in main
    ret = c.parse(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/main.py", line 94, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/cd.py", line 174, in do
    self.doCommand()
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/cd.py", line 485, in doCommand
    ripIfNotRipped(i + 1)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/cd.py", line 414, in ripIfNotRipped
    number, len(self.itable.tracks), extra))
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/common/program.py", line 603, in ripTrack
    runner.run(t)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 479, in run
    self._loop.run()
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/gstreamer.py", line 151, in stop
    task.Task.stop(self)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 157, in stop
    self._notifyListeners('stopped')
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 237, in _notifyListeners
    method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 373, in stopped
    self.stop()
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/program/cdparanoia.py", line 548, in stop
    task.MultiSeparateTask.stop(self)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 154, in stop
    import traceback; traceback.print_stack()
Ripping track 1 of 16 (try 3): 01. Steven Wright - And Now Little Green Bag….flac
Ripping track 1 of 16 (try 4): 01. Steven Wright - And Now Little Green Bag….flac
ERROR: stopping task which is already stopped
  File "/usr/bin/whipper", line 9, in <module>
    load_entry_point('whipper==0.4.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/main.py", line 27, in main
    ret = c.parse(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/main.py", line 94, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/cd.py", line 174, in do
    self.doCommand()
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/cd.py", line 485, in doCommand
    ripIfNotRipped(i + 1)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/rip/cd.py", line 414, in ripIfNotRipped
    number, len(self.itable.tracks), extra))
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/common/program.py", line 603, in ripTrack
    runner.run(t)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 479, in run
    self._loop.run()
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/gstreamer.py", line 151, in stop
    task.Task.stop(self)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 157, in stop
    self._notifyListeners('stopped')
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 237, in _notifyListeners
    method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 373, in stopped
    self.stop()
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/program/cdparanoia.py", line 548, in stop
    task.MultiSeparateTask.stop(self)
  File "/usr/lib/python2.7/site-packages/whipper-0.4.0-py2.7.egg/morituri/extern/task/task.py", line 154, in stop
    import traceback; traceback.print_stack()
Ripping track 1 of 16 (try 5): 01. Steven Wright - And Now Little Green Bag….flac
ERROR [ 4862] "rip"                            rip               Nov 13 11:53:11      Giving up on track 1 after 5 times (morituri/rip/cd.py:423)
Giving up on track 1 after 5 times
 `
Debug logile: 
[whipper.log.gz](https://github.com/JoeLametta/whipper/files/587714/whipper.log.gz)

Look forward to the fix.  Thanks.

**Comment by aereaux** [comment]
As far as I can tell, this only happens with one cd (on one particular track) for me.  It's not identified with MusicBrainz, but it's [this](http://www.freedb.org/freedb/classical/1b115b14) on freedb, and it's the second disc of [this cd](http://www.arkivmusic.com/classical/album.jsp?album_id=9990).  It happens wuth the 9th track.

**Comment by stochashtic** [comment]
I haven't compared our debug logs, so maybe mine is a different cause.  But I am unable to rip any CD.  I can move this to a new thread if advised as such by the developers.

**Comment by JoeLametta** [comment]
Thanks for the bug reports.

Unfortunately I still haven't got the time to analyze the logfiles (which are really verbose^). I'll post again in case of any updates.

Something which is not so clear is if this issue happens only using whipper or it affects morituri too.

^ The logger function is going to be completely rewritten to provide more meaningful data.

**Comment by aereaux** [comment]
It also happens for me using morituri.

**Comment by JoeLametta** [comment]
> It also happens for me using morituri.

OK, same error message (`ERROR: stopping task which is already stopped`), right?

**Comment by aereaux** [comment]
Yeah.  In case it matters, it happened while doing `rip offset find`, and it left a whole bunch of cd-paranoia processes around (I assume because it tried a bunch of other offsets after finding the first one failed).

**Comment by JoeLametta** [comment]
@aereaux @stochashtic 

Could you repost the logfiles using an updated version of whipper (following [these instructions](https://github.com/JoeLametta/whipper#bug-reports--feature-requests))?

Thanks

**Comment by aereaux** [comment]
Here are the updated logs.  I am using whipper 0.4.2-1 from the arch linux AUR.
[whipper.log.gz](https://github.com/JoeLametta/whipper/files/709530/whipper.log.gz)

**Comment by JoeLametta** [comment]
> Here are the updated logs. I am using whipper 0.4.2-1 from the arch linux AUR.

From a quick review it seems to me that this bug may be related to GStreamer usage in whipper (which is scheduled for removal, will be done  soon™). So my suggestion is to wait until that removal has been completed, then check if the issue still affects whipper.

Thanks

PS: #101 too seems to be related to the same issue.

**Comment by JoeLametta** [comment]
@aereaux @stochashtic 

GStreamer has been dropped.
Could you try testing if this issue still occurs using whipper's latest version?

Thanks in advance,

Joe

**Comment by aereaux** [comment]
The error I get now is this:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/morituri/common/checksum.py", line 49, in _crc32
    w = wave.open(self.path)
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 131, in initfp
    raise Error, 'file does not start with RIFF id'
wave.Error: file does not start with RIFF id
exception Error at /usr/lib/python2.7/wave.py:131: initfp(): file does not start with RIFF id
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/morituri/common/checksum.py", line 49, in _crc32
    w = wave.open(self.path)
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 131, in initfp
    raise Error, 'file does not start with RIFF id'
Error: file does not start with RIFF id
```

**Comment by JoeLametta** [comment]
> The error I get now is this:

Thanks, could you also provide a debug logfile (instructions [HERE](https://github.com/JoeLametta/whipper#bug-reports--feature-requests))?

**Comment by aereaux** [comment]
Here.  This was done using commit 17b70ce82b2feeb69d27a07e43abf09ff7c049e6.
[whipper.log.gz](https://github.com/JoeLametta/whipper/files/952832/whipper.log.gz)

**Comment by stochashtic** [comment]
Works fine for me now.

**Comment by aereaux** [comment]
@stochashtic What version are you using?

**Comment by stochashtic** [comment]
Sorry, I am using commit `5b2639a`.

**Comment by aereaux** [comment]
Unfortunately I still get the RIFF id error with the most recent git commit (gb331f53)

**Comment by aereaux** [comment]
I think that the RIFF id is a separate problem (#136).  As far as I can tell, the original problem is fixed, so I'm closing this.
