### ISSUE TITLE
ImportError: No module named log

### ISSUE THREAD

**Issue by thomas-mc-work** [JoeLametta/whipper#64]
I receive this error in the latest version when starting the rip command:

```Python
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 11, in <module>
load_entry_point('whipper==0.3.0', 'console_scripts', 'rip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2249, in load
return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2255, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.3.0-py2.7.egg/morituri/rip/main.py", line 9, in <module>
from morituri.common import log, logcommand, common, config, directory
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.3.0-py2.7.egg/morituri/common/log.py", line 27, in <module>
from morituri.extern.log import log as externlog
ImportError: No module named log
```

**Comment by JoeLametta** [comment]
It looks you're missing whipper's flog dependency, how did you build & install whipper?

Try following updated installation instructions [here](https://github.com/JoeLametta/whipper/tree/readme-rewrite#installation).

**Comment by thomas-mc-work** [comment]
Alright, I missed the preceding parts before `python2 setup.py install`.

Thank you for your always good and fast replies!

**Comment by JoeLametta** [comment]
> Thank you for your always good and fast replies!

You're welcome!
