### ISSUE TITLE
Whipper attempts to rip with no CD inserted

### ISSUE THREAD

**Issue by BoBeR182** [JoeLametta/whipper#81]
Expected result:
Error message saying empty drive and whipper ejecting it for me.

What happened:
```python
whipper cd rip
Using configured read offset 6
Checking device /dev/sr0
WARNING:root:cdrdao read-toc failed: return code is non-zero: 1
Traceback (most recent call last):
  File "/usr/sbin/whipper", line 11, in <module>
    load_entry_point('whipper==0.4.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 27, in main
    ret = c.parse(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 94, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/morituri/common/logcommand.py", line 62, in parse
    command.Command.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/site-packages/morituri/rip/cd.py", line 86, in do
    self.device)
  File "/usr/lib/python2.7/site-packages/morituri/common/program.py", line 136, in getFastToc
    t = cdrdao.ReadTOCTask(device)
  File "/usr/lib/python2.7/site-packages/morituri/program/cdrdao.py", line 61, in ReadTOCTask
    return read_toc(device, fast_toc=True)
  File "/usr/lib/python2.7/site-packages/morituri/program/cdrdao.py", line 33, in read_toc
    raise e
subprocess.CalledProcessError: Command '['cdrdao', 'read-toc', '--fast-toc', '--device', '/dev/sr0', u'/tmp/tmph89lFh.cdrdao.read-toc.whipper']' returned non-zero exit status 1
```

**Comment by JoeLametta** [comment]
> Expected result:
> Error message saying empty drive and whipper ejecting it for me.

Thanks for the bug report.

The regression was introduced with https://github.com/JoeLametta/whipper/commit/d7f8557426798b69dff52e07205d3f75eb427dbd.
The way it's currently implemented is that `cdrdao.py` just checks for a non-zero exit status, otherwise it throws the exception you've seen.

@RecursiveForest Do you know if there is a simple way to improve this?

**Comment by RecursiveForest** [comment]
My apologies, missed this until just now. There is a simple fix for this I can implement shortly.

**Comment by RecursiveForest** [comment]
https://github.com/RecursiveForest/whipper/tree/cdrdao-nodisc should fix this (it doesn't eject, though, although we could if we wanted to after I look around some more to understand when whipper does/does not eject), but it depends on the argparse & logging PR, so I'm waiting until that's merged to PR this. By then I may have a comprehensive solution to when to eject or not.

**Comment by RecursiveForest** [comment]
This raises an important question I'd like other people to weigh in on: When should whipper eject the CD tray? Right now it ejects only during `whipper cd rip`: either on successful rip or if the metadata can't be retrieved.

**Comment by ArchangeGabriel** [comment]
@RecursiveForest I totally agree with you on all those points. ;)

**Comment by RecursiveForest** [comment]
https://github.com/JoeLametta/whipper/pull/93
